---
application:
  name: "manga-scraper"
  project: "scraper-manga"
  organization: "QoveryCommunity"
routers:
- name: "main-manga-scraper"
  routes:
  - application_name: "manga-scraper"
    paths:
    - "/*"
